PART03/katalog-ukm/ukmummu/admin/routes.py
from flask import Flask, render_template, redirect, url_for, Blueprint, flash, request
from ukmummu import app,db,bcrypt
from ukmummu.models import Tindustri, Tukm, Tkategori, Tproduk, Tadmin
from ukmummu.admin.forms import industri_F, ukm_F, kategori_F, eindustri_F, eukm_F, ekategori_F, eadmin_F

gadmin= Blueprint('gadmin',__name__)

@gadmin.route("/tes")
def tes():
    return "Selamat datang di pelatihan"

@gadmin.route("/dasboard")
def dasboard():
    industri=len(Tindustri.query.all())
    ukm=len(Tukm.query.all())
    produk=len(Tproduk.query.all())
    return render_template("t_admin/dasboard.html", industri=industri, ukm=ukm, produk=produk)

#CRUD DATA INDUSTRI
@gadmin.route("/industri", methods=['GET', 'POST'])
def industri():
    form=industri_F()
    data=Tindustri.query.all()
    if form.validate_on_submit():
        add= Tindustri(industri=form.industri.data, ket=form.ket.data)
        db.session.add(add)
        db.session.commit()
        flash('Data berhasil ditambahkan','warning')
        return redirect(url_for('gadmin.industri'))
    return render_template("t_admin/industri.html", dataidustri=data, form=form)


@gadmin.route("/hapusindustri/<id>", methods=['GET', 'POST'])
def hapus_industri(id):
    qindustri=Tindustri.query.get(id)
    db.session.delete(qindustri)
    db.session.commit()
    flash('Data Berhasil Di hapus','warning')
    return redirect(url_for('gadmin.industri')) 

@gadmin.route("/editindustri/<int:ed_id>/update", methods=['GET', 'POST'])
def update_industri(ed_id):
    dataindustri=Tindustri.query.get_or_404(ed_id)
    form=eindustri_F()
    if form.validate_on_submit():
        dataindustri.industri=form.industri.data
        dataindustri.ket=form.ket.data
        db.session.commit()
        flash('Data Berhasil Di ubah','warning')
        return redirect(url_for('gadmin.industri'))
    elif request.method=="GET":
        form.industri.data=dataindustri.industri
        form.ket.data=dataindustri.ket
    return render_template('t_admin/eindustri.html', form=form)
#BATAS CRUD INDUSTRI

#CRUD ANGGOTA UKM
@gadmin.route("/anggota", methods=['GET', 'POST'])
def anggota():
    form=ukm_F()
    data=Tukm.query.all()
    form.industriid.choices = [(str(tindustri.id), tindustri.industri) for tindustri in Tindustri.query.all()]
    if form.validate_on_submit():
        pass_hash= bcrypt.generate_password_hash(form.noizin.data). decode('utf-8')
        add= Tukm(nama_ukm=form.namaukm.data, no_izin=form.noizin.data, industri_id=form.industriid.data, nama_pemilik=form.namapemilik.data, no_ktp=form.noktp.data, username=form.namaukm.data, password=pass_hash )
        db.session.add(add)
        db.session.commit()
        flash('Data berhasil ditambahkan, username:nama ukm dan password:no izin','warning')
        return redirect(url_for('gadmin.anggota'))
    return render_template("t_admin/anggota.html", dataukm=data,form=form )


@gadmin.route("/hapusukm/<id>", methods=['GET', 'POST'])
def hapus_ukm(id):
    qukm=Tukm.query.get(id)
    db.session.delete(qukm)
    db.session.commit()
    flash('Data Berhasil Di hapus','warning')
    return redirect(url_for('gadmin.anggota')) 


@gadmin.route("/editukm/<int:ed_id>/update", methods=['GET', 'POST'])
def update_ukm(ed_id):
    dataukm=Tukm.query.get_or_404(ed_id)
    form=eukm_F()
    form.industriid.choices = [(str(tindustri.id), tindustri.industri) for tindustri in Tindustri.query.all()]
    if form.validate_on_submit():
        pass_hash= bcrypt.generate_password_hash(form.noizin.data). decode('utf-8')
        dataukm.nama_ukm=form.namaukm.data
        dataukm.no_izin=form.noizin.data
        dataukm.industri_id=form.industriid.data
        dataukm.nama_pemilik=form.namapemilik.data
        dataukm.no_ktp=form.noktp.data
        dataukm.username=form.namaukm.data
        dataukm.password=pass_hash
        db.session.commit()
        flash('Data Berhasil Di ubah','warning')
        return redirect(url_for('gadmin.anggota'))
    elif request.method=="GET":
        form.namaukm.data=dataukm.nama_ukm
        form.noizin.data=dataukm.no_izin
        form.industriid.data=dataukm.ukms.industri
        form.namapemilik.data=dataukm.nama_pemilik
        form.noktp.data=dataukm.no_ktp
    return render_template('t_admin/eanggota.html', form=form)

#batas CRUD Anggota UKM


#CRUD kategori

@gadmin.route("/kategori", methods=['GET', 'POST'])
def kategori():
    form=kategori_F()
    data=Tkategori.query.all()
    return render_template("t_admin/kategori.html", datakategori=data, form=form)


#buatlah fungsi edit dan hapusnya!

# batas CRUD kategori




#CRUD admin
@gadmin.route("/admin", methods=['GET', 'POST'])
def admin():
    form=eadmin_F()
    dataadmin=Tadmin.query.all()
    return render_template("t_admin/admin.html", data=dataadmin, form=form)


@gadmin.route("/edithakakses/<int:ed_id>/update", methods=['GET', 'POST'])
def update_admin(ed_id):
    dataadmin=Tadmin.query.get_or_404(ed_id)
    form=eadmin_F()
    if form.validate_on_submit():
        cekpass= Tadmin.query.filter_by(password=form.password.data).first()
        if cekpass and bcrypt.check_password_hash(cekpass.password, form.password.data):
            pass_hash= bcrypt.generate_password_hash(form.passwordbaru.data). decode('utf-8')
            dataadmin.username=form.usernamebaru.data
            dataadmin.password=pass_hash
            db.session.commit()
            flash('Hak Akses Berhasil di ubah','warning')
            return redirect(url_for('gadmin.dasboard'))
        else:
            flash('password yang dimasukan salah, silahkan coba kembali !!','danger')
            return redirect(url_for('gadmin.admin'))
       
    return render_template("t_admin/eadmin.html", data=dataadmin, form=form)

#batas crud admin

PART03/katalog-ukm/ukmummu/templates/t_admin/admin.html
{% extends "t_admin/base.html" %}

{% block konten%}
    
    <!-- Begin Page Content -->
    <div class="container-fluid">
    
                        <!-- Page Heading -->
                        <div class="d-sm-flex align-items-center justify-content-between mb-4">
                            <h1 class="h3 mb-0 text-gray-800">Hak Akses</h1>
                            <!--bagian bisa dimasukan form seacrh dari masing-masing data-->
                            <p></p>
                        </div>
    
                        <!-- Content Row -->
                    
                        <div class="row">
    
                            <!-- Data indusrti -->
                            <div class="col-xl-4 col-lg-5">
                                <div class="card shadow mb-4">
                                    <!-- Card Header - Dropdown -->
                                    <div
                                        class="card-header py-3 d-flex flex-row align-items-center justify-content-between">
                                        <h6 class="m-0 font-weight-bold text-primary">Ubah Hak Akses</h6>
                                       
                                    </div>
                                    <!-- Card Body -->
                                    <div class="card-body">
                                        
                                             
                                        <div class="form-group">
                                            <p>Klik tautan di bawah ini untuk mengubah Hak Akses, Pastikan kamu masih mengetahui username dan password sebelumnya.</p>
                                            {% for di in data %}
                                            <a "btn btn-danger" href="{{url_for('gadmin.update_admin', ed_id=di.id)}}">Ubah Hak Akses</a>
                                            {% endfor %}
                                        </div>

                                        
                                        
                                    </div>
                                </div>
                            </div>
    
                            <!-- Input Kategori -->
                            <div class="col-xl-8 col-lg-7">
                                </div>
                                    <!-- Card Body -->
                                   
                        </div>
    
    </div></div>      
    
    </div>
                    <!-- /.container-fluid -->
{% endblock%}
    

PART03/katalog-ukm/ukmummu/templates/t_admin/anggota.html
{% extends "t_admin/base.html" %}

{% block konten%}
    
    <!-- Begin Page Content -->
    <div class="container-fluid">
    
                        <!-- Page Heading -->
                        <div class="d-sm-flex align-items-center justify-content-between mb-4">
                            <h1 class="h3 mb-0 text-gray-800">Anggota UKM</h1>
                            <!--bagian bisa dimasukan form seacrh dari masing-masing data-->
                            <p></p>
                        </div>
    
                        <!-- Content Row -->
                    
                        <div class="row">
    
                            <!-- Data Kategori -->
                            <div class="col-xl-4 col-lg-5">
                                <div class="card shadow mb-4">
                                    <!-- Card Header - Dropdown -->
                                    <div
                                        class="card-header py-3 d-flex flex-row align-items-center justify-content-between">
                                        <h6 class="m-0 font-weight-bold text-primary">Input UKM</h6>
                                       
                                    </div>
                                    <!-- Card Body -->
                                    <div class="card-body">
                                        <!--form inputan-->
                                       <p>bagian untuk meletakan form inputan</p>
                                       <form method="POST">
                                        {{form.hidden_tag()}}

                                    <div class="form-group">
                                        {{form.namaukm.label(class="form-control-label")}}
                                        {% if form.namaukm.errors %}
                                             {{form.namaukm(class="form-control is-invalid")}}
                                    
                                             <div class="invalid-feedback">
                                                 {%for error in form.namaukm.errors %}
                                                 <span>{{error}}</span>
                                                 {% endfor %}
                                             </div>
                                        {%else%}
                                            {{form.namaukm(class="form-control")}}
                                        
                                        {%endif%}
                                    </div>

                                    <div class="form-group">
                                        {{form.noizin.label(class="form-control-label")}}
                                        {% if form.noizin.errors %}
                                             {{form.noizin(class="form-control is-invalid")}}
                                    
                                             <div class="invalid-feedback">
                                                 {%for error in form.noizin.errors %}
                                                 <span>{{error}}</span>
                                                 {% endfor %}
                                             </div>
                                        {%else%}
                                            {{form.noizin(class="form-control")}}
                                        
                                        {%endif%}
                                    </div>

                                    <div class="form-group">
                                        {{form.industriid.label(class="form-control-label")}}
                                        {% if form.industriid.errors %}
                                             {{form.industriid(class="form-control is-invalid")}}
                                    
                                             <div class="invalid-feedback">
                                                 {%for error in form.industriid.errors %}
                                                 <span>{{error}}</span>
                                                 {% endfor %}
                                             </div>
                                        {%else%}
                                            {{form.industriid(class="form-control")}}
                                        
                                        {%endif%}
                                    </div>

                                    <div class="form-group">
                                        {{form.namapemilik.label(class="form-control-label")}}
                                        {% if form.namapemilik.errors %}
                                             {{form.namapemilik(class="form-control is-invalid")}}
                                    
                                             <div class="invalid-feedback">
                                                 {%for error in form.namapemilik.errors %}
                                                 <span>{{error}}</span>
                                                 {% endfor %}
                                             </div>
                                        {%else%}
                                            {{form.namapemilik(class="form-control")}}
                                        
                                        {%endif%}
                                    </div>

                                    <div class="form-group">
                                        {{form.noktp.label(class="form-control-label")}}
                                        {% if form.noktp.errors %}
                                             {{form.noktp(class="form-control is-invalid")}}
                                    
                                             <div class="invalid-feedback">
                                                 {%for error in form.noktp.errors %}
                                                 <span>{{error}}</span>
                                                 {% endfor %}
                                             </div>
                                        {%else%}
                                            {{form.noktp(class="form-control")}}
                                        
                                        {%endif%}
                                    </div>
                                    
                                    <div class="form-group">
                                        {{form.submit(class="btn btn-primary")}}
                                    </div>

                                    

                                    
                                    </form>
                                    </div>
                                </div>
                            </div>
    
                            <!-- Input Kategori -->
                            <div class="col-xl-8 col-lg-7">
                                <div class="card shadow mb-4">
                                    <!-- Card Header - Dropdown -->
                                    <div
                                        class="card-header py-3 d-flex flex-row align-items-center justify-content-between">
                                        <h6 class="m-0 font-weight-bold text-primary">Data UKM</h6>
                                        
                                    </div>
                                    <!-- Card Body -->
                                    <div class="card-body">
                                        <div class="card-body">
                                            <div class="table-responsive">
                                                <table class="table table-bordered table-hover" id="dataTable" width="100%" cellspacing="0">
                                                    <thead>
                                                        <tr>
                                                            <th>Nama UKM</th>
                                                            <th>No Izin</th>
                                                            <th>Industri</th>
                                                            <th>Nama Pemiliki</th>
                                                            <th>Proses</th>
                                                        </tr>
                                                    </thead>
                                                    <tfoot>
                                                        <tr>
                                                            <th>Nama UKM</th>
                                                            <th>No Izin</th>
                                                            <th>Industri</th>
                                                            <th>Nama Pemiliki</th>
                                                            <th>Proses</th>
                                                        </tr>
                                                    </tfoot>
                                                    <tbody>
                                                        {% for du in dataukm %}
                                                        <tr>
                                                            <td>{{du.nama_ukm}}</td>
                                                            <td>{{du.no_izin}}</td>
                                                            <td>{{du.industri_id}}/{{du.ukms.industri}}</td>
                                                            <td>{{du.nama_pemilik}}</td>
                                                            <td><a class="btn btn-sm btn-warning" href="{{url_for('gadmin.update_ukm', ed_id=du.id)}}">Edit</a>  <a class="btn btn-sm btn-danger" href="/hapusukm/{{du.id}}" onclick="return confirm('Yakin data akan di hapus')">Hapus</a></td>
                                                            
                                                        </tr>
                                                        {% endfor %}
                                                    </tbody>
                                                    </table>
                                    </div>
                                </div>
                            </div>
                        </div>
    
    </div></div>      
    
    </div>
                    <!-- /.container-fluid -->
{% endblock%}
    

PART03/katalog-ukm/ukmummu/templates/t_admin/dasboard.html
{% extends "t_admin/base.html" %}

{% block dasboard%}
    
    <!-- Begin Page Content -->
    <div class="container-fluid">
    
                        <!-- Page Heading -->
                        <div class="d-sm-flex align-items-center justify-content-between mb-4">
                            <h1 class="h3 mb-0 text-gray-800">Selamat Datang !</h1>
                            
                        </div>
    
                        <!-- Content Row -->
                    
                        <div class="row">

                            <!-- Earnings (Monthly) Card Example -->
                        <div class="col-xl-3 col-md-6 mb-4">
                                <div class="card border-left-primary shadow h-100 py-2">
                                    <div class="card-body">
                                        <div class="row no-gutters align-items-center">
                                            <div class="col mr-2">
                                                <div class="text-xs font-weight-bold text-primary text-uppercase mb-1">
                                                    DATA INDUSTRI</div>
                                                <div class="h5 mb-0 font-weight-bold text-gray-800">{{industri}}</div>
                                            </div>
                                            <div class="col-auto">
                                                <i class="fas fa-calendar fa-2x text-gray-300"></i>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
    
                            <!-- Earnings (Monthly) Card Example -->
                            <div class="col-xl-3 col-md-6 mb-4">
                                <div class="card border-left-success shadow h-100 py-2">
                                    <div class="card-body">
                                        <div class="row no-gutters align-items-center">
                                            <div class="col mr-2">
                                                <div class="text-xs font-weight-bold text-success text-uppercase mb-1">
                                                    DATA UMK</div>
                                                <div class="h5 mb-0 font-weight-bold text-gray-800">{{ukm}}</div>
                                            </div>
                                            <div class="col-auto">
                                                <i class="fas fa-dollar-sign fa-2x text-gray-300"></i>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>


                            <!-- Earnings (Monthly) Card Example -->
                            <div class="col-xl-3 col-md-6 mb-4">
                                    <div class="card border-left-warning shadow h-100 py-2">
                                        <div class="card-body">
                                            <div class="row no-gutters align-items-center">
                                                <div class="col mr-2">
                                                    <div class="text-xs font-weight-bold text-warning text-uppercase mb-1">
                                                        DATA RODUK</div>
                                                    <div class="h5 mb-0 font-weight-bold text-gray-800">{{produk}}</div>
                                                </div>
                                                <div class="col-auto">
                                                    <i class="fas fa-dollar-sign fa-2x text-gray-300"></i>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                </div>
    
                            
    
                            
    
                           
                            
                        </div>
    
    </div></div>      
    
    </div>
                    <!-- /.container-fluid -->
{% endblock%}
    

PART03/katalog-ukm/ukmummu/templates/t_admin/industri.html
{% extends "t_admin/base.html" %}

{% block konten%}
    
    <!-- Begin Page Content -->
    <div class="container-fluid">
    
                        <!-- Page Heading -->
                        <div class="d-sm-flex align-items-center justify-content-between mb-4">
                            <h1 class="h3 mb-0 text-gray-800">Industri</h1>
                            <!--bagian bisa dimasukan form seacrh dari masing-masing data-->
                            <p></p>
                        </div>
    
                        <!-- Content Row -->
                    
                        <div class="row">
    
                            <!-- Data indusrti -->
                            <div class="col-xl-4 col-lg-5">
                                <div class="card shadow mb-4">
                                    <!-- Card Header - Dropdown -->
                                    <div
                                        class="card-header py-3 d-flex flex-row align-items-center justify-content-between">
                                        <h6 class="m-0 font-weight-bold text-primary">Input Jenis Industri</h6>
                                       
                                    </div>
                                    <!-- Card Body -->
                                    <div class="card-body">
                                        <!--form inputan-->
                                        <p>bagian untuk meletakan form inputan</p>
                                        <form method="POST">
                                            {{form.hidden_tag()}}

                                        <div class="form-group">
                                            {{form.industri.label(class="form-control-label")}}
                                            {% if form.industri.errors %}
                                                 {{form.industri(class="form-control is-invalid")}}
                                        
                                                 <div class="invalid-feedback">
                                                     {%for error in form.industri.errors %}
                                                     <span>{{error}}</span>
                                                     {% endfor %}
                                                 </div>
                                            {%else%}
                                                {{form.industri(class="form-control")}}
                                            
                                            {%endif%}
                                        </div>

                                        <div class="form-group">
                                            {{form.ket.label(class="form-control-label")}}
                                            {% if form.ket.errors %}
                                                 {{form.ket(class="form-control is-invalid")}}
                                        
                                                 <div class="invalid-feedback">
                                                     {%for error in form.ket.errors %}
                                                     <span>{{error}}</span>
                                                     {% endfor %}
                                                 </div>
                                            {%else%}
                                                {{form.ket(class="form-control")}}
                                            
                                            {%endif%}
                                        </div>

                                        <div class="form-group">
                                            {{form.submit(class="btn btn-primary")}}
                                        </div>

                                        </form>
                                    </div>
                                </div>
                            </div>
    
                            <!-- Input Kategori -->
                            <div class="col-xl-8 col-lg-7">
                                <div class="card shadow mb-4">
                                    <!-- Card Header - Dropdown -->
                                    <div
                                        class="card-header py-3 d-flex flex-row align-items-center justify-content-between">
                                        <h6 class="m-0 font-weight-bold text-primary">Data Industri</h6>
                                        
                                    </div>
                                    <!-- Card Body -->
                                    <div class="card-body">
                                        <div class="card-body">
                                            <div class="table-responsive">
                                                <table class="table table-bordered table-hover" id="dataTable" width="100%" cellspacing="0">
                                                    <thead>
                                                        <tr>
                                                            <th>Jenis Industri</th>
                                                            <th>Keterangan</th>
                                                            <th>Proses</th>
                                                        </tr>
                                                    </thead>
                                                    <tfoot>
                                                        <tr>
                                                            <th>Jenis Industri</th>
                                                            <th>Keterangan</th>
                                                            <th>Proses</th>
                                                        </tr>
                                                    </tfoot>
                                                    <tbody>
                                                        {% for di in dataidustri %}
                                                        <tr>
                                                            <td>{{di.industri}}</td>
                                                            <td>{{di.ket}}</td>
                                                            <td><a class="btn btn-sm btn-warning" href="{{url_for('gadmin.update_industri', ed_id=di.id)}}">Edit</a>  <a class="btn btn-sm btn-danger" href="/hapusindustri/{{di.id}}" onclick="return confirm('Yakin data akan di hapus')">Hapus</a></td>
                                                            
                                                        </tr>
                                                        {% endfor %}
                                                    </tbody>
                                                    </table>
                                    </div>
                                </div>
                            </div>
                        </div>
    
    </div></div>      
    
    </div>
                    <!-- /.container-fluid -->
{% endblock%}
    